# If not running interactively, don't do anything
[[ $- != *i* ]] && return

### Utility functions ###

_command_exists() {
    command -v "$1" &> /dev/null
}

### Custom commands/helpers ###

init_dev_flake() {
    # TODO: use devenv for this instead
	# "https://github.com/the-nix-way/dev-templates"

	local lang=$1

	if [ -z "$lang" ]; then
		echo "Usage: init_dev_flake <language>" >&2
		return 1
	fi

	local repo="https://github.com/the-nix-way/dev-templates"
	local cache_dest="${HOME}/.cache/flake-dev-templates"
	if [[ -d "$cache_dest" ]]; then
		git -C "$cache_dest" fetch --prune
	else
		git clone --depth 1 "$repo" "$cache_dest"
	fi

	echo "Try initialising dev flake for $lang..."
	if nix flake init -t "path:${cache_dest}#${lang}"; then
        if _command_exists direnv; then direnv allow; fi
		echo "Okie!"
		return 0
	else
		return 1
	fi
}

if _command_exists fzf; then
	eval "$(fzf --zsh)"
	if _command_exists fd; then export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'; fi
fi

if _command_exists devenv; then source <(devenv hook zsh); fi

## Opts ###
setopt COMPLETE_ALIASES

### Envs/Path/Other exports ###
if [ -d $HOME/.cargo/env ]; then
    source "$HOME/.cargo/env"
    PATH=$PATH:$HOME/.cargo/bin
fi

### Aliases ###
alias grep="grep --color=auto"
alias ls="ls -a --color=auto"
if command -v eza &> /dev/null; then
    alias ls="eza -hl --icons=auto"
    alias ll="eza -hla --icons=auto"
    alias l.="eza -hl -d .* --icons=auto 2> /dev/null || true" # Suppressing the error code when no matches are found, there's probably a more robust way to do this
fi
if command -v nvim &> /dev/null; then
    alias v="nvim";
fi
if _command_exists lazygit; then alias lg="lazygit"; fi
if _command_exists zoxide; then
    eval "$(zoxide init zsh --cmd cd)"
    alias zi="__zoxide_zi"
fi

### Binds ###
# List functions with `print -l ${(ok)functions}`
bindkey "^[[3~" delete-char
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^H" backward-delete-word
bindkey "^[[3;5~" delete-word
bindkey "^I" menu-complete
bindkey "^[[Z" reverse-menu-complete
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

### History ###
HISTFILE=~/.zhistory
HISTSIZE=10000
SAVEHIST=10000
setopt histignorealldups
setopt SHARE_HISTORY

### Case-insensitive path-completion ###
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' menu select

if _command_exists starship; then eval "$(starship init zsh)"; fi

### Autocompletion ###
autoload bashcompinit && bashcompinit
autoload -Uz +X compinit && compinit

if _command_exists zoxide; then
  eval "$(zoxide init zsh)"
fi

if _command_exists asdf; then
  fpath=(${ASDF_DIR}/completions $fpath)
fi

if _command_exists devpod; then
    source <(devpod completion zsh)
fi

if _command_exists kubectl; then
    source <(kubectl completion zsh)
fi

if _command_exists aws && _command_exists aws_completer; then
    complete -C '$(which aws_completer)' aws
fi

if _command_exists eksctl; then
    source <(eksctl completion zsh)
fi

export PATH

if [ -z "$SSH_CONNECTION" ]; then
    if [ -e "$HOME/.var/app/com.bitwarden.desktop/data/.bitwarden-ssh-agent.sock" ]; then
        export SSH_AUTH_SOCK="$HOME/.var/app/com.bitwarden.desktop/data/.bitwarden-ssh-agent.sock"
    fi
fi
